export const categories = [
    "All",
    "Music",
    "React routers",
    "Computer programming",
    "Reverberation",
    "Movie musicals",
    "India national cricket team",
    "News",
    "Mixes",
    "1990s",
    "Telugu cinema",
    // "Live",
    // "Dramedy",
    // "Dubbing",
    // "Indian soap opera",
    // "Cricket",
    // "Football",
    // "Learn Coding",
  ];